### ISSUE TITLE
why do we move a contrib into a indepent repo ?

### ISSUE THREAD

**Issue by yupbank** [tensorflow/kfac#1]
this is https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/kfac right ?

**Comment by duckworthd** [comment]
Hi @yupbank,

To add more features! While all code added to `tf.contrib` is maintained by the core TensorFlow team (and must meet the documented API requirements), this library will add new features that leverage some of TensorFlow's undocumented APIs.
