### ISSUE TITLE
supported data_format 'nchw'

### ISSUE THREAD

**Issue by jlee4176901** [tensorflow/kfac#22]
It seems that data_format "nchw" is not properly supported? 

E.g in "class ConvDiagonalFactor(DiagonalFactor):".

If so, are there any plans to include them since data_format then seems misleading?

**Comment by james-martens** [comment]
I think it might work in some contexts but I'm not sure anymore since I haven't touched those parts of the code in years and don't have the bandwidth to.  If NCHW is supported, which it probably is in some contexts, it isn't well tested.  I would recommend using NHWC.
