### ISSUE TITLE
Not support tf2.1?

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [tensorflow/kfac#32]
I got an error: No module named 'tensorflow.contrib'

**Comment by leommiranda** [comment]
I assume that nowadays there is no support for tf2.1.

If you take a look at [.travis.yml](https://github.com/tensorflow/kfac/blob/master/.travis.yml) and [setup.py](https://github.com/tensorflow/kfac/blob/master/setup.py) files, you'll notice that the project requires [tensorflow](https://github.com/tensorflow/tensorflow) version higher than 1.14 and that it has been tested on the version 1.15.

**Comment by leomichalski** [comment]
[Duplicate issue](https://github.com/tensorflow/kfac/issues/30)
