### ISSUE TITLE
a potential bug in computing num_conv_locations

### ISSUE THREAD

**Issue by gd-zhang** [tensorflow/kfac#9]
https://github.com/tensorflow/kfac/blob/master/kfac/python/ops/fisher_blocks.py#L1119

It seems there is a bug in computing num_conv_locations. The current implementation doesn't take the padding into consideration. 

Let's say a conv kernel (3 * 3 * 10 * 10) with padding 0, num_conv_locations function gives 9 (I think it should be 1).

**Comment by duckworthd** [comment]
Good find! You're absolutely right -- the current definition of `num_conv_locations` is correct only when `padding == 'SAME'`. 

@gd-zhang Would you be willing to correct this? I can as well, but it may take some time...

**Comment by duckworthd** [comment]
(assigning to @gd-zhang for feedback).

**Comment by gd-zhang** [comment]
@duckworthd Just submitted the pull request.

**Comment by ShHsLin** [comment]
This bug is fixed already right?
